version: '3'

services:
  application:
    build: ./docker/php
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - db
    links:
      - db:dbserver
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
      MYSQL_USER: ${DOCKER_DB_USER}
      MYSQL_PASSWORD: ${DOCKER_DB_USER_PASSWORD}
    ports:
      - '3306:3306'
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application
